### PR TITLE
BaseTools: Add LoongArch architecture support in the DataType.py script

### PR DESCRIPTION
**Pull request by kilaterlee**
Changes to the Python code used to build the LoongArch platform.

Signed-off-by: Chao Li <lichao@loongson.cn>

### CODE REVIEW

**Comment by kilaterlee** [comment]
Dear @lgao4 @BobCF @mdkinney @changab ,

I have submitted a new PR in BaseTools python code to add a new arch called LoongArch, which is use for the CI build. Please review it. :)

Thanks,

Chao Li

**Comment by mdkinney** [comment]
I do not think this change is required.

I updated BaseTools to allow any new CPU Archs to be added without BaseTools source changes earlier this year.
It was synced to this project in this PR: https://github.com/tianocore/edk2-basetools/pull/9.

Have you tried just adding a new tool chain with support for this new arch in a DSC file or tools_def.txt?  What breaks?

**Comment by kilaterlee** [comment]
Hi @mdkinney,

The new Arch code is close to complate. I did the CI build in Azure and locally. I found the BaseTools which is in the CI environment is come from this code, so I modified the BaseTools python code in the locally CI environment, and then the CI build can run. If it not modified, it will tell me that the new Arch is not supported. I found that if CI BaseTools does not add new Arch support, Azure CI will report the same error.

I fact, I was added the cross-toolchain download address and add our new Arch support in edk2 CI frame located in our development repo. We just want to test whether our development repo code can be built and tested through the CI.

What should we do to enable the Azure CI to support our new Arch?

**Comment by mdkinney** [comment]
Perhaps the pip-requirements.txt in edk2 needs to be updated to a newer version of edk2-basetools???

**Comment by kilaterlee** [comment]
Hi @mdkinney ,

Okay, let me try today. In fact, our devel repo is updated every two days, I think if upstream updates the pip-requirements.txt, then our repo should follow upstream updates. Anyway, I will try it, any resoult I will let you know. :) 

Thanks,
Chao Li

**Comment by kilaterlee** [comment]
Hi @mdkinney ,

I tried to find the version in the edk2-basetools repo, but I couldn't find it.

Should I get the newer version number in edk2-basetools repo and modify the pip-requirements.txt in edk2? In current version edk2, a line in pip-requirements.txt written **edk2-basetools==0.1.2**, should this line be modified to the newer version?

Thanks,
Chao Li

**Comment by kilaterlee** [comment]
Hi Mike @mdkinney ,

If you have any other solutions to this issue, I would like to try it. Hope you reply.

Thanks,
Chao Li

**Comment by spbrogan** [comment]
can you try 0.1.6

See latest here:
https://pypi.org/project/edk2-basetools/

**Comment by mdkinney** [comment]
Is this PR still required?  Can it be closed?

**Comment by kilaterlee** [comment]
> Is this PR still required? Can it be closed?

Yes, this problem has been sloved, I should close it now.

**Pull request closed without merging**
